florimondmanca/djangorestframework-api-key

- README.md
- rest_framework_api_key/__init__.py
- Fix the example usage of `HasAPIKey` as a global permission class
- Provide clearer description of the two available permission classes
Fixes #1
> Fix #1, update README.md

- makemigrations.py
- rest_framework_api_key/admin.py
- rest_framework_api_key/models.py
- runtests.py
- tests/factory.py
- tests/mixins.py
Type annotations (3.5+ style) were being used in some tests and `admin.py`. Not sure how tests passed, but they are not supposed to be compatible with Python 3.4, and so were removed.
Other minor fixes.
> Improve compatibility with Python 3.4

- .bumpversion.cfg
- Pipfile
- Pipfile.lock
- README.md
[bumpversion](https://pypi.org/project/bumpversion/) is a tool helping with versioning. It is now configured to automatically update the package's version in `__init__.py` and create a tagged commit ready to be pushed (with `git push --tags`) for a new PyPI deployment.
Example with a dry run of a patch bump:
```bash
$ bumpversion --dry-run --verbose patch
Reading config file .bumpversion.cfg:
[bumpversion]
current_version = 0.2.2
commit = True
tag = True
[bumpversion:file:rest_framework_api_key/__init__.py]
Parsing version '0.2.2' using regexp '(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)'
Parsed the following values: major=0, minor=2, patch=2
Attempting to increment part 'patch'
Values are now: major=0, minor=2, patch=3
Dry run active, won't touch any files.
Parsing version '0.2.3' …
```
> Automate versioning with bumpversion

- README.md
- example_project/example/settings.py
- rest_framework_api_key/apps.py
- rest_framework_api_key/checks.py
- rest_framework_api_key/permissions.py
- rest_framework_api_key/settings.py
- tests/mixins.py
- Use a namespace for djangorestframework-api-key specific settings: `DRF_API_KEY_*`
- Update header settings to use this namespace
- Add system checks so users are told to update their settings (below is an example output on the updated example project)
```
$ python manage.py check
SystemCheckError: System check identified some issues:
ERRORS:
<Settings "example.settings">: (rest_framework_api_key.E001) Setting API_TOKEN_HEADER has been deprecated in v0.3
HINT: Use the DRF_API_KEY_TOKEN_HEADER setting instead.
<Settings "example.settings">: (rest_framework_api_key.E002) Setting API_SECRET_KEY_HEADER has been deprecated in v0.3
HINT: Use the DRF_API_KEY_SECRET_KEY_HEADER setting instead.
System check identified 2 issues (0 silenced).
```
To be released as v0.3.
Fix #13
> Add settings namespace

- rest_framework_api_key/models.py
- tests/test_api_key_model.py
- tests/test_has_api_key.py
Hashers like bcrypt(256) have periods.
Use .partition instead of .split in this case.
https://docs.python.org/3/library/stdtypes.html#str.partition
> Fix hashers that emit periods (Fix #22)

- .travis.yml
- scripts/install
Parametrization of the installed Django version via `$DJANGO_VERSION` wasn't working on CI because the environment variable wasn't accounted for in the installation process.
`scripts/install` now works both locally and on CI, yielding the desired behavior in both environments.
> Fix install script for CI

- tests/conftest.py
- tests/test_permissions.py
- tests/test_permissions_combination.py
- tests/test_permissions_custom.py
- tests/utils.py
Prompted by https://github.com/florimondmanca/djangorestframework-api-key/pull/102#issuecomment-581119016
> Refactor view_with_permissions as a utility function

- tests/test_admin.py
Prompted by https://github.com/florimondmanca/djangorestframework-api-key/pull/102#issuecomment-581119016
> Refactor admin tests

- tests/test_legacy_key_generator.py
The current fake custom key generator based on the interface before #62 was depending on code from the current package state. This isn't stable, so this PR removes any dependency other than Django.
> Freeze legacy key generator

- CHANGELOG.md
- docs/guide.md
- src/rest_framework_api_key/models.py
- tests/test_model.py
This PR exposes a new method, `BaseAPIKeyManager.get_from_key()`, for retrieving APIKey objects based on a generated key that is not stored in the database. In addition, it refactors the `BaseAPIKeyManager.is_valid()` method to use the new `.get_from_key()` method.
Fixes #92.
* Confirm the three new tests pass
* Run `scripts/serve`, navigate to http://localhost:8000/guide/#programmatic-usage, and confirm the new bulleted section at the end of `Programmatic usage` looks good
> Add and document BaseAPIKeyManager.get_from_key()

- docs/index.md
Lack of indent meant the content was not displayed in the admonition block.
> Fix broken admonitions in docs home page

- scripts/check
- scripts/makemigrations
**Motivation**
- `scripts/makemigrations` was outdated.
- Run in `--check` mode as part of `scripts/check` so that checks fail if migrations are lagging behind.
> Fix makemigrations script and check it on CI

- ci/azure-pipelines.yml
- setup.py
Per [Supported Versions](https://www.djangoproject.com/download/#supported-versions):
- Django 2.0 is EOL since April 2019.
- Django 2.1 is EOL since Jan 2020.
We should try to keep the maintenance burden as low as possible, so let's drop support for them in 2.0.
Refs #100
> Drop support for `django<2.2`

- MANIFEST.in
This is required for `py.typed` to be included in the package build (sdist/wheel), and type hints to be detected by mypy.
Refs #88, #122, cleanup for #127
> [2.0.0 Cleanup] Add MANIFEST.in

- docs/guide.md
Fixes [issue 97](https://github.com/florimondmanca/djangorestframework-api-key/issues/97).
Add `/src/` to documentation links to avoid 404 error.
> Add /src/ to source code paths in documentation

- docs/guide.md
URL on [Should I use API Keys?](https://florimondmanca.github.io/djangorestframework-api-key/guide/#api-key-models) within warning box is broken and leads to a 404 not found resource.
> Fix Broken URL

- docs/security.md
Fix statement
It is treated with the same level of care ~than~ passwords:  (fix)
It is treated with the same level of care **as** passwords:   (correction)
Besides, ~you do NOT~ recommend using this package for authentication (fix)
Besides, ~it is NOT recommended~ to use this package for authentication. (correction)
> Fix Statement

- guide/index.html
This will fix the broken "Should I use API keys?" documentation link.
Closes: #176
> fix "Should I use API keys?" documentation link Closes: #176

- scripts/check
- scripts/lint
- tests/conftest.py
- tests/test_admin.py
- tests/test_model.py
- tests/test_permissions.py
- tests/test_permissions_combination.py
- tests/test_permissions_custom.py
- tests/utils.py
I realized by reviewing #175 that only `tests/conftest.py` was subject to code formatting (autoflake, black, etc). I think we want _all_ of `tests/` to be code-formatted and linted.
So this PR updates `scripts/check` and `scripts/lint`, and contains the result of running `scripts/lint`.
> Format code under tests/

- ci/azure-pipelines.yml
* Use new standardized docs-build job
* Templates v3.4 use ubuntu-18.04 by default, preventing an issue on check and docs jobs that would run deprecated ubuntu-16.04 otherwise (refs https://github.com/florimondmanca/djangorestframework-api-key/pull/175#issuecomment-915201866):
```
##[error]This is a scheduled Ubuntu 16.04 brownout. Ubuntu 16.04 LTS environment will be removed on September 20, 2021. For more details, see https://github.com/actions/virtual-environments/issues/3287
,##[error]The remote provider was unable to process the request.
Started: mar. at 16:06
Duration: 1d 20h 54m
```
> Update CI templates to 3.4

- docs/guide.md
- src/rest_framework_api_key/permissions.py
- tests/conftest.py
- tests/test_model.py
- tests/test_permissions.py
This Pull request will add the ability to specify a custom API Keyword by overriding the `KeyParser` class. 
Example:
```py
from rest_framework_api_key.permissions import BaseHasAPIKey, KeyParser
class BearerKeyParser(KeyParser):
keyword = "Bearer"
class HasAPIKey(BaseHasAPIKey):
key_parser = BearerKeyParser()
```
This will allow you to use Bearer
Closes: #174
> Add support for custom API keyword

- CONTRIBUTING.md
- scripts/publish
Follow-up to #182 
Azure Pipelines is not yet configured to push to GitHub (`mkdocs gh-deploy` pushes to the `gh-pages` branch), so `scripts/docs gh-deploy` fails on CI. See: https://dev.azure.com/florimondmanca/public/_build/results?buildId=1236&view=logs&j=1d8102be-1b57-5858-ccce-e1484c113a01&t=c37d61ed-8649-56ca-791d-73e7296a747c
For now, let's hint release managers to deploy the docs manually after a release.
> Deploy docs manually

- ci/azure-pipelines.yml
- requirements.txt
- setup.py
- test_project/heroes/apps.py
Quick overhaul of deps and package versions:
- Test under Django 2.2 and 3.2 only, as 3.0 is deprecated and 3.1 will soon be (see [Django - Supported versions](https://www.djangoproject.com/download/#supported-versions))
- Update CI templates and test under Python 3.10 (update trove classifiers, adding Python 3.9 and 3.10)
- Update dev dependencies
> Bump deps, add official Django 3.2 and Py3.9/3.10 support

- Makefile
- requirements.txt
- tests/test_admin.py
- tools/install_django.sh
Bump dev dependencies, and test against Django 4.0 as a first step towards #205.
Also fixes CI that stopped installing using `$DJANGO_VERSION` as #198 forgot to port this part over: https://github.com/florimondmanca/djangorestframework-api-key/pull/198/files#diff-6233345de4867c7ccf72bac1fc1067988d2a4c8e1ab9a746956eafccf88cfed2L15-L17
> Bump dev dependencies, fix CI installing django from $DJANGO_VERSION

- requirements.txt
- setup.cfg
- src/rest_framework_api_key/__init__.py
- tests/test_admin.py
- tests/test_compatibility.py
- tests/test_migrations.py
- tests/test_permissions.py
Closes #96 
* Applies relevant `pragma: no cover` invocations
* Add missing admin and permission tests.
* Test migrations using the _fantastic_ [django-test-migrations](https://github.com/wemake-services/django-test-migrations) package. (This was created in Nov 2019. Not available at the time of version 1.4, which contained #62 that added the 0004 migration. Would have been _so_ helpful to ensure migrations work in various use cases!)
> Reach 100% test coverage

- test_project/project/urls.py
- test_project/project/views.py
- tests/conftest.py
- tests/test_test_project.py
This PR adds a few example routes to the `test_project`.
As per https://github.com/florimondmanca/djangorestframework-api-key/issues/173#issuecomment-1146677315, it turns out having some example routes in the `test_project` to run requests against is quite handy for debugging, investigation, etc.
(This might need tests to preserve 100% coverage...)
> Add routes to test_project

- CHANGELOG.md
- setup.py
- src/rest_framework_api_key/permissions.py
- tests/test_permissions.py
Closes #150 
This essentially reverts #25 when DRF 3.14.0 or above is detected.
Not reverting in all cases prevents breakage (i.e. API keys not being checked anymore if using them with a bitwise OR) if people upgrade DRF-api-key while still using an older DRF.
> Drop redundant .has_object_permission impl on DRF 3.14.0 or above

- docs/security.md
> detaining -> obtaining
I think that is what was meant.
> responsability -> responsibility
> Fix typos in security docs

- README.md
- docs/index.md
- docs/security.md
- src/rest_framework_api_key/crypto.py
- src/rest_framework_api_key/models.py
- tests/test_hashers.py
* Uses sha512 instead of Django's password hashers for hashing API keys. As [outlined here](https://github.com/florimondmanca/djangorestframework-api-key/issues/173#issuecomment-1561951736), the purpose of password hashing is to make brute force attempts very hard by making a password check slow (~100ms+). That is likely unnecessary for keys that are randomly generated like in this project. The sha512 hasher is much faster (<1ms).
* Transparently upgrades any keys encountered that use the slow password hashers with the sha512 hasher whenever that key is used.
Ref: https://github.com/florimondmanca/djangorestframework-api-key/issues/173
* ~~If the basic code is approved, the docs will need a significant overhaul to explain this change. I figured I'd hold off on that until there's consensus …
> Use a fast key hasher instead of password hashers

- CHANGELOG.md
- README.md
- docs/guide.md
- docs/index.md
- docs/upgrade/3.0.md
- mkdocs.yml
- src/rest_framework_api_key/__init__.py
- Use faster SHA512-based key hasher instead of password hashers. Reduces server load by making API key validation orders of magnitude faster (10x to 30x according to estimations, network latency aside). Hashed key will be transparently upgraded the first time `.is_valid()` is called. (Pull #244, Pull #251)
- Dropped support for Python 3.7, which has reached EOL. (Pull #247)
- Drop redundant `.has_object_permission()` implementation on `BaseHasAPIKey` when using DRF 3.14.0 or above. (Pull #240)
- Add official support for Python 3.11. (Pull #247)
> Version 3.0.0
