.travis.yml
README.md
rest_framework_api_key/__init__.py

- Add Django 2.1 in build matrix in `.travis.yml`.
- Update supported versions (and add associated shields.io badges) in `README.md`.
Fixes #3

Fix #3, Add support for Django 2.1

---

.travis.yml
Pipfile
Pipfile.lock

See [CVE-2018-16984](https://nvd.nist.gov/vuln/detail/CVE-2018-16984).

Fix vulnerability when using django >=2.1, <2.1.2

---

CHANGELOG.md
rest_framework_api_key/permissions.py
tests/conftest.py
tests/test_has_api_key.py

Implement has_object_permissions on HasAPIKey

---

.travis.yml
CHANGELOG.md
Pipfile
Pipfile.lock
README.md
tests/test_has_api_key.py

Test default password hashers

---

CHANGELOG.md
rest_framework_api_key/permissions.py
tests/conftest.py
tests/heroes/permissions.py
tests/test_permissions.py
tests/test_permissions_custom.py

Add permission base classes

---

Pipfile
Pipfile.lock
README.md
docs/guide.md
docs/index.md
docs/security.md
mkdocs.yml

Already live at https://florimondmanca.github.io/djangorestframework-api-key :rocket:

Add docs site

---

.travis.yml
setup.py

Add official Python 3.8 support

---

scripts/check
scripts/lint
setup.cfg
tests/conftest.py

Type-check conftest.py

---

tests/test_checks.py
tests/test_legacy_key_generator.py

Refs https://github.com/florimondmanca/djangorestframework-api-key/pull/102#issuecomment-581119016, refs #89.

Refactor and type non-permission tests

---

.travis.yml
scripts/check
scripts/docs
scripts/env
scripts/install
scripts/lint
scripts/publish
scripts/serve
scripts/test

Refs #104 
- Update `scripts/` so that they work on Windows too.
- Add Windows to the test matrix.

Add Windows tooling compatibility

---

ci/azure-pipelines.yml
ci/templates/install.yml
requirements.txt

Motivated by https://github.com/florimondmanca/djangorestframework-api-key/issues/113#issuecomment-609062799

Test PostgreSQL on CI

---

ci/azure-pipelines.yml
scripts/docs
scripts/serve

Switch to a single `docs` script instead of `scripts/docs` (for build) and `scripts/serve` (for serve).

Update docs script

---

CHANGELOG.md
docs/upgrade/1.0.md
mkdocs.yml

- Drop links to versions.
- Add PR numbers when available.
- Move 1.0 upgrade guide to the docs site.
- Various copy fixes.

Update changelog format

---

docs/guide.md

Refs #88, #122 
Pre-requisite for #100

Document typing support

---

docs/upgrade/2.0.md
mkdocs.yml

Add 2.0 upgrade guide

---

mkdocs.yml

Fixes #133 
Refs https://bugs.debian.org/956920

Fix docs site copyright notice

---

requirements.txt
scripts/check
scripts/lint
setup.cfg
tests/conftest.py

See: https://timothycrosley.github.io/isort/CHANGELOG/#500-penny-july-4-2020

Use isort 5

---

requirements.txt
tests/conftest.py

Committed via https://github.com/asottile/all-repos

Use and pin Black 20

---

docs/guide.md

Fix for [Issue #144](https://github.com/florimondmanca/djangorestframework-api-key/issues/144)
* Updated the programmatic usage example based on the discussion above

Update guide - fix programmatic usage example

---

docs/guide.md

Clarify that full generated API key should be used

---

ci/azure-pipelines.yml
requirements.txt
setup.py

Add support for Django 4.2

---

src/rest_framework_api_key/admin.py
src/rest_framework_api_key/models.py

- added `gettext_lazy` so that translations for different messages and prompts can be supported.

✅ added `I18N` support

---

src/rest_framework_api_key/permissions.py
tests/test_permissions.py

Keyword of header now is compared in exact way
